/**
 * Seed script — single entry point for all PolarX fixtures.
 *
 * Phases 0–2:  the three real research stations, demo missions, demo shipments.
 * Phase 3:     256 inventory items generated by a deterministic loop to hit the
 *              target demo distribution (adequate 142 / low-stock 63 /
 *              critical 26 / out-of-stock 25 — the Phase 7 slide targets).
 * Phase 4–7:   personnel, emergency alerts, users + station capacity updates
 *              are appended by later phases.
 *
 * The generator is deterministic (seeded PRNG), so two runs on the same
 * database produce the same dataset. All inserts are idempotent by natural key.
 *
 * Run with: npm run seed
 */
const { sequelize, Station, Mission, Shipment, InventoryItem, Personnel, EmergencyAlert, User } = require('../models');
const bcrypt = require('bcryptjs');
const { ensurePostGIS } = require('./db');
const { DEFAULT_CHECKLISTS, buildChecklist } = require('../controllers/emergencyController');

// Phase 7 — demo login (also documented in the README).
const DEMO_USER = {
  name: 'Commander Polar',
  email: 'commander@polarx.in',
  password: 'polarx-demo-2026',
  role: 'commander',
  station: 'Bharati',
};

// --- Deterministic PRNG (mulberry32) ---------------------------------------
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace(arr, rand) {
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rand() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function randInt(rand, min, max) {
  return min + Math.floor(rand() * (max - min + 1));
}

const STATIONS = [
  {
    name: 'Bharati',
    region: 'Antarctica',
    location: { type: 'Point', coordinates: [76.1869, -69.4075] }, // Larsemann Hills, East Antarctica
    capacity: 47, // peak summer berthing
    founded_year: 2012,
  },
  {
    name: 'Maitri',
    region: 'Antarctica',
    location: { type: 'Point', coordinates: [11.7322, -70.7655] }, // Schirmacher Oasis
    capacity: 25, // realistic year-round crew (Phase 7 target)
    founded_year: 1989,
  },
  {
    name: 'Himadri',
    region: 'Arctic',
    location: { type: 'Point', coordinates: [11.935, 78.925] }, // Ny-Ålesund, Svalbard
    capacity: 12, // Phase 7 target (research station berthing incl. partners)
    founded_year: 2008,
  },
];

// Phase 1 fixtures — missions per station (idempotent by name).
const MISSIONS = [
  { name: '36th ISEA — Bharati Summer Resupply', station: 'Bharati', start_date: '2025-11-05', end_date: '2026-03-25', status: 'active', personnel_count: 42, cargo_count: 12 },
  { name: 'Bharati Wintering Crew Rotation', station: 'Bharati', start_date: '2026-10-15', end_date: '2027-03-10', status: 'planned', personnel_count: 24, cargo_count: 8 },
  { name: 'Maitri Resupply Mission 2026', station: 'Maitri', start_date: '2025-12-01', end_date: '2026-02-28', status: 'active', personnel_count: 25, cargo_count: 10 },
  { name: 'Maitri Winter Maintenance 2025', station: 'Maitri', start_date: '2025-04-01', end_date: '2025-05-20', status: 'completed', personnel_count: 18, cargo_count: 6 },
  { name: 'Himadri 2026 Summer Programme', station: 'Himadri', start_date: '2026-01-10', end_date: '2026-09-15', status: 'active', personnel_count: 9, cargo_count: 4 },
  { name: 'Himadri Logistics Trial Run', station: 'Himadri', start_date: '2025-08-20', end_date: '2025-09-05', status: 'completed', personnel_count: 6, cargo_count: 2 },
];

// Small manifests used by shipments below.
function manifest(entries) {
  return entries.map(([name, quantity]) => ({ name, quantity }));
}

// Phase 2 fixtures — demo shipments (destination text matches station names so
// the client can resolve route endpoints; current_location drives map markers).
const SHIPMENTS = [
  {
    name: 'Supplies to Bharati Station',
    origin: 'Goa, India',
    destination: 'Bharati',
    mission: '36th ISEA — Bharati Summer Resupply',
    status: 'delivered',
    eta: '2026-01-20T00:00:00.000Z',
    current_location: { lat: -69.4075, lng: 76.1869 }, // at Bharati
    items: manifest([['Food rations (MRE)', 240], ['Fresh provisions', 36], ['Lab consumables', 80]]),
  },
  {
    name: 'Equipment to Maitri Station',
    origin: 'Cape Town, South Africa',
    destination: 'Maitri',
    mission: 'Maitri Resupply Mission 2026',
    status: 'in-transit',
    eta: '2026-09-28T00:00:00.000Z',
    current_location: { lat: -62.4, lng: 19.8 }, // mid Southern Ocean
    items: manifest([['Generator spares', 12], ['Snow vehicles', 3]]),
  },
  {
    name: 'Medical Supplies to Himadri Station',
    origin: 'Longyearbyen, Svalbard',
    destination: 'Himadri',
    mission: 'Himadri 2026 Summer Programme',
    status: 'delayed',
    eta: '2026-09-02T00:00:00.000Z',
    current_location: { lat: 77.9, lng: 11.4 }, // weather hold near Svalbard
    items: manifest([['Pharmaceutical kit', 18], ['First-aid consumables', 60]]),
  },
  {
    name: 'Fuel & Spares to Bharati Station',
    origin: 'Cape Town, South Africa',
    destination: 'Bharati',
    mission: '36th ISEA — Bharati Summer Resupply',
    status: 'in-transit',
    eta: '2026-10-04T00:00:00.000Z',
    current_location: { lat: -58.1, lng: 42.5 },
    items: manifest([['Aviation fuel (drum)', 40], ['Mechanical spares', 25]]),
  },
  {
    name: 'Scientific Instruments to Maitri Station',
    origin: 'Cape Town, South Africa',
    destination: 'Maitri',
    mission: 'Maitri Resupply Mission 2026',
    status: 'delivered',
    eta: '2026-02-10T00:00:00.000Z',
    current_location: { lat: -70.7655, lng: 11.7322 }, // at Maitri
    items: manifest([['Atmospheric sensors', 8], ['Data logging rigs', 5]]),
  },
  {
    name: 'Provisions to Himadri Station',
    origin: 'Tromsø, Norway',
    destination: 'Himadri',
    mission: 'Himadri 2026 Summer Programme',
    status: 'in-transit',
    eta: '2026-09-20T00:00:00.000Z',
    current_location: { lat: 75.1, lng: 8.6 },
    items: manifest([['Food rations', 120], ['Winter clothing', 45]]),
  },
  {
    name: 'Winter Clothing to Bharati Station',
    origin: 'Goa, India',
    destination: 'Bharati',
    mission: '36th ISEA — Bharati Summer Resupply',
    status: 'delayed',
    eta: '2026-08-27T00:00:00.000Z',
    current_location: { lat: -38.2, lng: 55.0 },
    items: manifest([['Extreme-cold parkas', 90], ['Insulated boots', 90]]),
  },
];

// ---------------------------------------------------------------------------
// Phase 4 — personnel (60 people; statuses target 42/6/6/6 per the demo
// slides). Rotations are generated relative to "today" so the 30-day rotation
// timeline always has entries regardless of when the seed is run.
// ---------------------------------------------------------------------------

const PERSONNEL_NAMES = [
  'Dr. Arjun Rao', 'Dr. Meera Krishnan', 'Capt. Vikram Singh', 'Lt. Ananya Iyer',
  'Dr. Rohan Deshmukh', 'Dr. Priya Menon', 'S. Ganesh Kumar', 'A. Shreya Nair',
  'Dr. Karthik Subramaniam', 'Dr. Divya Pillai', 'Cmdr. Rajesh Warrier', 'Dr. Nandini Joshi',
  'Er. Aditya Kulkarni', 'Er. Sneha Patil', 'Er. Varun Malhotra', 'Er. Kavya Reddy',
  'Er. Mohan Das', 'Er. Lakshmi Venkatesan', 'Dr. Siddharth Bose', 'Dr. Anjali Menon',
  'A. Ramesh Babu', 'B. Sunitha Devi', 'C. Prakash Rao', 'D. Jyothi Lakshmi',
  'E. Harish Chandra', 'F. Padma Priya', 'G. Suresh Kumar', 'H. Uma Shankar',
  'I. Madhavi Latha', 'J. Venkatesh Iyer', 'K. Geetha Raman', 'L. Balaji Prasad',
  'M. Revathi Subramanian', 'N. Chandra Sekhar', 'O. Deepika Rani', 'P. Manoj Kumar',
  'Q. Swathi Chandran', 'R. Arvind Krishnan', 'S. Janaki Devi', 'T. Natarajan',
  'U. Vijaya Lakshmi', 'V. Sanjay Menon', 'W. Anita Verghese', 'X. Kiran Bedi-Desai',
  'Y. Rahul Sharma', 'Z. Preethi Raghavan', 'Dr. Farhan Qureshi', 'Dr. Ishita Banerjee',
  'Er. Nikhil Agarwal', 'Er. Pallavi Kulkarni', 'Dr. Vivek Chandra', 'Dr. Swapna Iyer',
  'Er. Ashok Nambiar', 'Er. Rekha Varma', 'Dr. Manish Tiwari', 'Dr. Shalini Mishra',
  'Er. Deepak Bora', 'Er. Neha Gupta', 'Dr. Amitabh Sinha', 'Dr. Ritu Saxena',
];

const PERSONNEL_ROLES = [
  { role: 'Station Commander', quals: ['Polar Operations Leadership', 'Crisis Response Training'] },
  { role: 'Deputy Station Commander', quals: ['Logistics Management', 'Expedition Planning'] },
  { role: 'Medical Officer', quals: ['MBBS', 'Wilderness & Expedition Medicine'] },
  { role: 'Staff Nurse', quals: ['B.Sc Nursing', 'Basic Life Support'] },
  { role: 'Glaciologist', quals: ['PhD Glaciology', 'Polar Field Safety'] },
  { role: 'Meteorologist', quals: ['M.Sc Meteorology', 'Automatic Weather Station Ops'] },
  { role: 'Atmospheric Scientist', quals: ['PhD Atmospheric Chemistry', 'Balloon Sonde Operations'] },
  { role: 'Marine Biologist', quals: ['PhD Marine Biology', 'SCUBA Diver'] },
  { role: 'Geologist', quals: ['PhD Geology', 'Field Mapping'] },
  { role: 'Seismologist', quals: ['M.Sc Seismology', 'Sensor Network Operations'] },
  { role: 'Electrical Engineer', quals: ['B.Tech Electrical', 'Generator Maintenance'] },
  { role: 'Mechanical Engineer', quals: ['B.Tech Mechanical', 'Snow Vehicle Repair'] },
  { role: 'Electronics Engineer', quals: ['B.Tech ECE', 'Satellite Communications'] },
  { role: 'Diesel Mechanic', quals: ['ITI Diesel Mechanics', 'Cold-Start Systems'] },
  { role: 'Communication Officer', quals: ['HF/VHF Radio License', 'INMARSAT Operations'] },
  { role: 'IT Support Engineer', quals: ['B.Sc Computer Science', 'Network Administration'] },
  { role: 'Logistics Officer', quals: ['Supply Chain Management', 'Customs Clearance'] },
  { role: 'Storekeeper', quals: ['Inventory Management', 'Forklift Certified'] },
  { role: 'Chef', quals: ['Culinary Arts', 'High-Altitude Nutrition'] },
  { role: 'Assistant Cook', quals: ['Food Safety (HACCP)', 'Bakery Skills'] },
  { role: 'Plumber', quals: ['ITI Plumbing', 'Water Treatment Operations'] },
  { role: 'Electrician', quals: ['ITI Electrical', 'Solar Array Maintenance'] },
  { role: 'Carpenter', quals: ['ITI Carpentry', 'Prefab Construction'] },
  { role: 'Field Guide', quals: ['Mountaineering Certification', 'Crevice Rescue'] },
  { role: 'Field Assistant', quals: ['Polar Field Safety', 'Snowmobile License'] },
  { role: 'Laboratory Technician', quals: ['M.Sc Chemistry', 'Sample Handling'] },
  { role: 'Doctor', quals: ['MBBS', 'Emergency Medicine'] },
];

const PERSONNEL_STATUS_PLAN = { 'on-duty': 42, 'in-field': 6, 'at-base': 6, 'on-leave': 6 };
const PERSONNEL_STATION_PLAN = { Bharati: 26, Maitri: 20, Himadri: 14 };

function planPersonnel() {
  const rand = mulberry32(20260905);
  const stationPlan = [];
  for (const [name, weight] of Object.entries(PERSONNEL_STATION_PLAN)) {
    for (let i = 0; i < weight; i += 1) stationPlan.push(name);
  }
  const statusPlan = [];
  for (const [status, count] of Object.entries(PERSONNEL_STATUS_PLAN)) {
    for (let i = 0; i < count; i += 1) statusPlan.push(status);
  }
  shuffleInPlace(stationPlan, rand);
  shuffleInPlace(statusPlan, rand);

  const coordsByName = {};
  for (const station of STATIONS) coordsByName[station.name] = station.location.coordinates; // [lng, lat]

  return PERSONNEL_NAMES.map((name, i) => {
    const status = statusPlan[i];
    const station = stationPlan[i];
    const role = PERSONNEL_ROLES[i % PERSONNEL_ROLES.length];

    // A few people rotate out inside the next 30 days (for the timeline demo);
    // everyone else is comfortably mid-rotation.
    const daysToEnd = i < 4 ? randInt(rand, 2, 29) : randInt(rand, 45, 340);
    const rotationEnd = daysFromNowIso(daysToEnd);
    const rotationStart = daysFromNowIso(daysToEnd - randInt(rand, 150, 210)); // ~5–7 months prior

    let currentLocation = null;
    if (status === 'in-field') {
      const [lng, lat] = coordsByName[station];
      const dLat = (rand() - 0.5) * 0.5;
      const dLng = (rand() - 0.5) * 0.5;
      currentLocation = { type: 'Point', coordinates: [lng + dLng, lat + dLat] }; // near-station field camp
    }

    return { name, role: role.role, quals: role.quals, status, station, rotationStart, rotationEnd, currentLocation };
  });
}

// ---------------------------------------------------------------------------
// Phase 3 — inventory generator (256 items; status distribution is a target,
// so the plan is shuffled deterministically rather than rolled randomly).
// ---------------------------------------------------------------------------

// Items that carry an expiry date in reality (food, medical, lab consumables).
const PERISHABLE_FRAGMENTS = [
  'rations', 'meals', 'provisions', 'flour', 'rice', 'dal', 'oil', 'spices', 'sugar', 'tea',
  'milk', 'butter', 'cheese', 'egg', 'biscuits', 'chocolate', 'vitamin', 'bandages', 'antiseptic',
  'gloves', 'pharmaceutical', 'antibiotics', 'analgesics', 'cream', 'tablets', 'reagents',
  'samples', 'slides', 'ink', 'batteries (aa)',
];

const INVENTORY_BASES = [
  'Oxygen cylinders', 'Aviation fuel (ltr)', 'Diesel fuel (ltr)', 'Kerosene (ltr)',
  'Food rations (MRE)', 'Freeze-dried meals', 'Fresh provisions', 'Wheat flour', 'Rice',
  'Dal (pulses)', 'Cooking oil', 'Spices & condiments', 'Sugar', 'Tea & coffee', 'Powdered milk',
  'Butter (canned)', 'Cheese (canned)', 'Egg powder', 'Biscuits & snacks', 'Chocolate bars',
  'Vitamin supplements', 'First-aid bandages', 'Antiseptic solution', 'Surgical gloves',
  'Pharmaceutical kit', 'Antibiotics (course)', 'Analgesics', 'Water purification tablets',
  'Water jerrycans', 'Snow boots', 'Extreme-cold parkas', 'Insulated gloves', 'Balaclavas',
  'Thermal underwear', 'UV sunglasses', 'Sunscreen', 'Sleeping bags', 'Expedition tents',
  'Ice axes', 'Dynamic ropes', 'Carabiners', 'Crampons', 'Ski sets', 'Snow shovels',
  'Generator spares', 'Engine oil', 'Hydraulic fluid', 'Air filters', 'Spark plugs',
  'AA batteries', 'Lead-acid batteries', 'Solar panels', 'Wind turbine blades', 'Fuel hoses',
  'Welding rods', 'Duct tape rolls', 'Static ropes', 'Sealing kits', 'Insulation panels',
  'Lab reagents', 'Sample vials', 'Cryo gloves', 'Microscope slides', 'Data logging rigs',
  'GPS units', 'Satellite phones', 'Radio transceivers', 'Antenna spares', 'Weather sensors',
  'Wind gauges', 'Barometers', 'Min/max thermometers', 'Snow sample bags', 'Ice core drills',
  'Lumber (treated)', 'Steel sheets', 'Anti-corrosion paint', 'LED bulbs', 'Fuses',
  'Circuit breakers', 'Power cable', 'Data cable', 'Hand tool sets', 'Power tool sets',
  'Fire extinguishers', 'Smoke detectors', 'CO2 scrubber canisters', 'HEPA filters',
  'Waste bags', 'Cleaning chemicals', 'Paper rolls', 'Printer ink', 'Stationery packs',
];

const INVENTORY_SUFFIXES = ['', ' (reserve)', ' (field)', ' (winter)', ' (primary)', ' (backup)', ' (heavy-duty)', ' (spare)'];

// Station weight per item → roughly 115 / 90 / 51 of the 256 rows.
const STATION_WEIGHTS = { Bharati: 115, Maitri: 90, Himadri: 51 };
const INVENTORY_STATUS_PLAN = {
  adequate: 142,
  'low-stock': 63,
  critical: 26,
  'out-of-stock': 25,
};

function planInventoryRows() {
  const rand = mulberry32(20260904); // fixed seed → identical data every run
  const stationPlan = [];
  for (const [name, weight] of Object.entries(STATION_WEIGHTS)) {
    for (let i = 0; i < weight; i += 1) stationPlan.push(name);
  }
  const statusPlan = [];
  for (const [status, count] of Object.entries(INVENTORY_STATUS_PLAN)) {
    for (let i = 0; i < count; i += 1) statusPlan.push(status);
  }
  shuffleInPlace(stationPlan, rand);
  shuffleInPlace(statusPlan, rand);

  return stationPlan.map((stationName, i) => {
    const status = statusPlan[i];
    const base = INVENTORY_BASES[i % INVENTORY_BASES.length];
    const suffix = INVENTORY_SUFFIXES[Math.floor(i / INVENTORY_BASES.length) % INVENTORY_SUFFIXES.length];
    const threshold = randInt(rand, 10, 240);

    // quantity chosen so deriveInventoryStatus() in the controller agrees:
    //  out-of-stock → 0; critical → 1..⌊0.3t⌋; low-stock → ⌊0.3t⌋+1..t; adequate → 3t..8t
    let quantity = 0;
    if (status === 'adequate') quantity = threshold * randInt(rand, 3, 8);
    else if (status === 'low-stock') quantity = randInt(rand, Math.floor(threshold * 0.3) + 1, threshold);
    else if (status === 'critical') quantity = randInt(rand, 1, Math.max(1, Math.floor(threshold * 0.3)));

    const perishable = PERISHABLE_FRAGMENTS.some((fragment) => base.toLowerCase().includes(fragment));
    let expiryDate = null;
    if (perishable) {
      const roll = rand();
      if (roll < 0.05) expiryDate = daysFromNowIso(randInt(rand, 0, 7)); // expiring within a week
      else if (roll < 0.14) expiryDate = daysFromNowIso(randInt(rand, 8, 30)); // expiring within a month
      else if (roll < 0.45) expiryDate = daysFromNowIso(randInt(rand, 31, 720));
    }

    const restockedDaysAgo = randInt(rand, 0, 90);
    const lastRestocked = new Date(Date.now() - restockedDaysAgo * 24 * 60 * 60 * 1000);

    return {
      stationName,
      name: `${base}${suffix}`.trim(),
      quantity,
      threshold,
      status,
      expiry_date: expiryDate,
      last_restocked: lastRestocked,
    };
  });
}

function daysFromNowIso(n) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

async function seed() {
  await ensurePostGIS();
  await sequelize.authenticate();
  await sequelize.sync();

  // --- Stations (Phase 0) ------------------------------------------------
  // Occupancy mirrors the Phase 4 personnel plan (26/20/14 on Bharati/Maitri/
  // Himadri). Existing rows are bumped to the current targets too, so a re-seed
  // after an earlier phase still converges on the Phase 7 numbers.
  const OCCUPANCY = { Bharati: 26, Maitri: 20, Himadri: 14 };
  const stationIdByName = {};
  for (const station of STATIONS) {
    const [row, created] = await Station.findOrCreate({
      where: { name: station.name },
      defaults: { ...station, status: 'active', personnel_on_station: OCCUPANCY[station.name] },
    });
    await row.update({ capacity: station.capacity, personnel_on_station: OCCUPANCY[station.name] });
    stationIdByName[station.name] = row.id;
    if (created) console.log(`✓ inserted station   ${station.name}`);
    else console.log(`• station exists     ${station.name}`);
  }

  // --- Missions (Phase 1) -------------------------------------------------
  let missionCount = 0;
  const missionIdByName = {};
  for (const mission of MISSIONS) {
    const [row, created] = await Mission.findOrCreate({
      where: { name: mission.name },
      defaults: {
        name: mission.name,
        station_id: stationIdByName[mission.station],
        start_date: mission.start_date,
        end_date: mission.end_date,
        status: mission.status,
        personnel_count: mission.personnel_count,
        cargo_count: mission.cargo_count,
      },
    });
    missionIdByName[mission.name] = row.id;
    if (created) {
      missionCount += 1;
      console.log(`✓ inserted mission    ${mission.name}`);
    }
  }
  if (missionCount === 0) console.log('• missions already seeded');

  // --- Shipments (Phase 2) -------------------------------------------------
  let shipmentCount = 0;
  for (const shipment of SHIPMENTS) {
    const [, created] = await Shipment.findOrCreate({
      where: { name: shipment.name },
      defaults: {
        name: shipment.name,
        origin: shipment.origin,
        destination: shipment.destination,
        mission_id: missionIdByName[shipment.mission] || null,
        status: shipment.status,
        eta: shipment.eta,
        current_location: { type: 'Point', coordinates: [shipment.current_location.lng, shipment.current_location.lat] },
        items: shipment.items,
      },
    });
    if (created) {
      shipmentCount += 1;
      console.log(`✓ inserted shipment   ${shipment.name}`);
    }
  }
  if (shipmentCount === 0) console.log('• shipments already seeded');

  // --- Personnel (Phase 4) -------------------------------------------------
  const personnelRows = planPersonnel();
  let personnelInserted = 0;
  for (const row of personnelRows) {
    const [, created] = await Personnel.findOrCreate({
      where: { name: row.name },
      defaults: {
        name: row.name,
        role: row.role,
        station_id: stationIdByName[row.station],
        qualifications: row.quals,
        rotation_start: row.rotationStart,
        rotation_end: row.rotationEnd,
        current_location: row.currentLocation,
        status: row.status,
      },
    });
    if (created) personnelInserted += 1;
  }
  if (personnelInserted > 0) {
    console.log(`✓ inserted ${personnelInserted} personnel records (target ${personnelRows.length})`);
  } else {
    console.log('• personnel already seeded');
  }

  // --- Emergency alerts (Phase 5) ------------------------------------------
  // Alerts are runtime data with relative timestamps, so they are only seeded
  // when the table is empty — never overwritten or duplicated on re-runs.
  if ((await EmergencyAlert.count()) === 0) {
    const rand = mulberry32(20260907);
    const allPersonnel = await Personnel.findAll({ attributes: ['id', 'station_id'] });
    const personFor = (stationName) => {
      const pool = allPersonnel.filter((p) => p.station_id === stationIdByName[stationName]);
      const pick = pool[Math.floor(rand() * Math.max(1, pool.length))];
      return pick ? pick.id : null;
    };
    const stationCoords = {};
    for (const station of STATIONS) stationCoords[station.name] = station.location.coordinates;
    const minutesAgo = (mins) => new Date(Date.now() - mins * 60 * 1000);

    const seedAlerts = [
      {
        alert_type: 'Fire', severity: 'critical', station: 'Bharati',
        description: 'Small fire reported in the generator annex; crew evacuating the area.',
        status: 'active', minutesAgo: 8, completedItems: 1,
      },
      {
        alert_type: 'Weather', severity: 'warning', station: 'Himadri',
        description: 'Blizzard warning — winds expected to exceed 45 kts overnight.',
        status: 'active', minutesAgo: 42, completedItems: 0,
      },
      {
        alert_type: 'Equipment Failure', severity: 'warning', station: 'Maitri',
        description: 'Primary diesel generator offline; running on backup unit.',
        status: 'active', minutesAgo: 95, completedItems: 2,
      },
      {
        alert_type: 'Medical', severity: 'info', station: 'Bharati',
        description: 'Crew member reported with mild hypothermia after field work; stable.',
        status: 'active', minutesAgo: 160, completedItems: 0,
      },
      {
        alert_type: 'Medical', severity: 'warning', station: 'Maitri',
        description: 'Frostbite injury treated; patient evacuated to station clinic.',
        status: 'resolved', minutesAgo: 300, completedItems: 4,
      },
      {
        alert_type: 'Weather', severity: 'info', station: 'Bharati',
        description: 'Whiteout conditions cleared; outdoor work resumed.',
        status: 'resolved', minutesAgo: 1560, completedItems: 4,
      },
      {
        alert_type: 'Other', severity: 'info', station: 'Himadri',
        description: 'Communication outage resolved after antenna realignment.',
        status: 'resolved', minutesAgo: 4320, completedItems: 4,
      },
    ];

    for (const seedAlert of seedAlerts) {
      const checklist = buildChecklist(seedAlert.alert_type);
      for (let i = 0; i < seedAlert.completedItems; i += 1) checklist[i].completed = true;
      await EmergencyAlert.create({
        triggered_by: personFor(seedAlert.station),
        type: seedAlert.alert_type,
        alert_type: seedAlert.alert_type,
        description: seedAlert.description,
        severity: seedAlert.severity,
        station_id: stationIdByName[seedAlert.station],
        location: { type: 'Point', coordinates: stationCoords[seedAlert.station] },
        timestamp: minutesAgo(seedAlert.minutesAgo),
        status: seedAlert.status,
        checklist_items: checklist,
        checklist_completed: seedAlert.completedItems === (DEFAULT_CHECKLISTS[seedAlert.alert_type] || []).length,
      });
    }
    console.log(`✓ inserted ${seedAlerts.length} emergency alerts (${seedAlerts.filter((a) => a.status === 'active').length} active, ${seedAlerts.filter((a) => a.status === 'resolved').length} resolved)`);
  } else {
    console.log('• emergency alerts already seeded');
  }

  // --- Users (Phase 7) -----------------------------------------------------
  // Demo account for the login flow; idempotent by email. The password is
  // hashed at seed time and never stored in plaintext.
  const [userRow, userCreated] = await User.findOrCreate({
    where: { email: DEMO_USER.email },
    defaults: {
      name: DEMO_USER.name,
      email: DEMO_USER.email,
      password_hash: await bcrypt.hash(DEMO_USER.password, 10),
      role: DEMO_USER.role,
      station_id: stationIdByName[DEMO_USER.station] || null,
    },
  });
  if (!userCreated) {
    // Re-seeds should converge too: re-hash so the documented password always
    // works even if the row predates this demo account block.
    await userRow.update({ password_hash: await bcrypt.hash(DEMO_USER.password, 10) });
  }
  console.log(userCreated ? `✓ inserted demo user ${DEMO_USER.email}` : `• demo user exists    ${DEMO_USER.email}`);

  // --- Inventory (Phase 3) -------------------------------------------------
  const inventoryRows = planInventoryRows();
  let inventoryInserted = 0;
  for (const row of inventoryRows) {
    const [, created] = await InventoryItem.findOrCreate({
      where: { station_id: stationIdByName[row.stationName], name: row.name },
      defaults: {
        station_id: stationIdByName[row.stationName],
        name: row.name,
        quantity: row.quantity,
        threshold: row.threshold,
        status: row.status,
        expiry_date: row.expiry_date,
        last_restocked: row.last_restocked,
      },
    });
    if (created) inventoryInserted += 1;
  }
  if (inventoryInserted > 0) {
    console.log(`✓ inserted ${inventoryInserted} inventory items (target ${inventoryRows.length})`);
  } else {
    console.log('• inventory already seeded');
  }

  console.log(
    `\nSeed complete — ${STATIONS.length} stations, ${MISSIONS.length} missions, ${SHIPMENTS.length} shipments, ` +
      `${inventoryRows.length} inventory items, ${personnelRows.length} personnel, emergency alerts seeded. ` +
      `Demo login: ${DEMO_USER.email} / ${DEMO_USER.password}`
  );
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('\n✗ Seeding failed:', err.message || err.code || err);
    process.exit(1);
  });
